{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Untitled0.ipynb","provenance":[],"authorship_tag":"ABX9TyNrNK4sDzOZ5i+UUvA5OxAX"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"lmhJ9dVIuVdn","executionInfo":{"status":"ok","timestamp":1627742985942,"user_tz":-330,"elapsed":1620,"user":{"displayName":"Sourabh Prakash","photoUrl":"","userId":"07057922078086223192"}},"outputId":"1e16078f-1364-4e00-8bd6-ed97b8fd8e9f"},"source":["from google.colab import drive \n","drive.mount('/content/drive', force_remount = True)\n"],"execution_count":36,"outputs":[{"output_type":"stream","text":["Mounted at /content/drive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":797},"id":"d6RHpKvIumJ1","executionInfo":{"status":"error","timestamp":1627742991558,"user_tz":-330,"elapsed":393,"user":{"displayName":"Sourabh Prakash","photoUrl":"","userId":"07057922078086223192"}},"outputId":"ebc98421-cf6e-431c-d326-fc3c06cb639b"},"source":["import os\n","os.chdir(\"drive/MyDrive/Cogni_AI/Hackathon_3\")"],"execution_count":37,"outputs":[{"output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"],"name":"stderr"},{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-37-939e519f2665>\", line 2, in <module>\n","    os.chdir(\"drive/MyDrive/Cogni_AI/Hackathon_3\")\n","OSError: [Errno 107] Transport endpoint is not connected: 'drive/MyDrive/Cogni_AI/Hackathon_3'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 1823, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 1132, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 313, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.7/inspect.py\", line 696, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.7/inspect.py\", line 725, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.7/inspect.py\", line 709, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.7/posixpath.py\", line 383, in abspath\n","    cwd = os.getcwd()\n","FileNotFoundError: [Errno 2] No such file or directory\n"],"name":"stdout"},{"output_type":"error","ename":"OSError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"]}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"C6pxXsdevq_X","executionInfo":{"status":"ok","timestamp":1627738707026,"user_tz":-330,"elapsed":2388,"user":{"displayName":"Sourabh Prakash","photoUrl":"","userId":"07057922078086223192"}},"outputId":"009f0a43-1631-443c-fbf2-c2882b18aa12"},"source":["#Installing required Packages\n","!pip install git+https://github.com/huggingface/neuralcoref.git\n","!pip install transformers==3.4.0\n","!pip install torch==1.6.0\n","!pip install git+https://github.com/thunlp/OpenNRE.gi\n"],"execution_count":35,"outputs":[{"output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","The folder you are executing pip from can no longer be found.\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","The folder you are executing pip from can no longer be found.\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","The folder you are executing pip from can no longer be found.\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","The folder you are executing pip from can no longer be found.\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"uiYrFK56xQ50","executionInfo":{"status":"ok","timestamp":1627738507659,"user_tz":-330,"elapsed":810,"user":{"displayName":"Sourabh Prakash","photoUrl":"","userId":"07057922078086223192"}},"outputId":"83eb4ac4-6da1-4b37-8f90-74fa9546bf56"},"source":["!pip install git+https://github.com/thunlp/OpenNRE.git"],"execution_count":29,"outputs":[{"output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","The folder you are executing pip from can no longer be found.\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"O4bL31iwxfyC","executionInfo":{"status":"ok","timestamp":1627738524518,"user_tz":-330,"elapsed":1012,"user":{"displayName":"Sourabh Prakash","photoUrl":"","userId":"07057922078086223192"}},"outputId":"05cf8c05-de3a-407a-b881-8e61490adfcf"},"source":["!pip install neuralcoref --no-binary neuralcoref"],"execution_count":30,"outputs":[{"output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n","The folder you are executing pip from can no longer be found.\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":36},"id":"mB6i6icBySGk","executionInfo":{"status":"ok","timestamp":1627738681454,"user_tz":-330,"elapsed":1036,"user":{"displayName":"Sourabh Prakash","photoUrl":"","userId":"07057922078086223192"}},"outputId":"514af1fc-111b-42bf-869c-216b02b137c4"},"source":["import spacy\n","spacy.__version__"],"execution_count":33,"outputs":[{"output_type":"execute_result","data":{"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"},"text/plain":["'2.2.4'"]},"metadata":{"tags":[]},"execution_count":33}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":815},"id":"7uxGJldBxsT5","executionInfo":{"status":"error","timestamp":1627738683286,"user_tz":-330,"elapsed":392,"user":{"displayName":"Sourabh Prakash","photoUrl":"","userId":"07057922078086223192"}},"outputId":"137983e2-be85-4969-b4b9-a3e8f408eaa3"},"source":["import opennre\n","model = opennre.get_model('wiki80_bert_softmax')"],"execution_count":34,"outputs":[{"output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"],"name":"stderr"},{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py\", line 2882, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-34-0132f0af7035>\", line 1, in <module>\n","    import opennre\n","ModuleNotFoundError: No module named 'opennre'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 1132, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 313, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py\", line 358, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.7/inspect.py\", line 696, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.7/inspect.py\", line 725, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.7/inspect.py\", line 709, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.7/posixpath.py\", line 383, in abspath\n","    cwd = os.getcwd()\n","FileNotFoundError: [Errno 2] No such file or directory\n"],"name":"stdout"},{"output_type":"error","ename":"ModuleNotFoundError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","","\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"]}]},{"cell_type":"code","metadata":{"id":"66-KHzhmx1bj"},"source":[""],"execution_count":null,"outputs":[]}]}